services:
  dbt_app:
    build:
      context: .
      dockerfile: ./apps/dbt_app/Dockerfile
    container_name: dbt_app
    volumes:
      - .apps/dbt_app/:/app
    env_file:
      - ./environments/dev/dbt_app/.env
  

  extract_app:
    build:
      context: ./extract_app
      dockerfile: Dockerfile
    container_name: extract_app
    volumes:
      - ./extract_app/:/app