data_app:
  target: stg
  outputs:
    stg:
      type: postgres
      host: "{{env_var('DBT_ENV_SECRET_HOST')}}"
      user: "{{env_var('DBT_ENV_SECRET_USERSTG')}}"
      password: "{{env_var('PDBT_ENV_SECRET_PASSWORDSTG')}}"
      dbname: "{{env_var('DBT_ENV_SECRET_DATABASE')}}"
      port: "{{5432 | int }}"
      schema: staging
      threads: 1
    rfnd:
      type: postgres
      host: "{{env_var('PGHOST')}}"
      user: "{{env_var('PGUSERRFND')}}"
      password: "{{env_var('PGPASSWORDRFND')}}"
      dbname: "{{env_var('PGDATABASE')}}"
      port: "{{env_var('PGPORT') | int }}"
      schema: refined
      threads: 1
    anltcs:
      type: postgres
      host: "{{env_var('PGHOST')}}"
      user: "{{env_var('PGUSERANLST')}}"
      password: "{{env_var('PGPASSWORDANLST')}}"
      dbname: "{{env_var('PGDATABASE')}}"
      port: "{{env_var('PGPORT') | int }}"
      schema: analytics
      threads: 1