version: 2

sources:
  - name: geografica
    description: nombres y códigos de los estados de la republica y sus municipios
    database: dengueappdb
    schema: staging
    tables:
      - name: estados
        columns:
          - name: cvegeoedo
          - name: nom_edo

      - name: municipios
        columns:
          - name: cvegeoedo
          - name: cvegeomuni
          - name: cve_mun
          - name: nom_mun

  - name: historic
    description: Este dataset se compone de datos historicos desde 2010 a 2023
    database: dengueappdb
    schema: staging
    tables:
      - name: modis_ndvi_historic
        description: >
          Contiene datos obtenidos por el satelite modis en granularidad diaria, por municipio.
          el ndvi (Natural Data Vegetation Index) indica la salud de la vegetación en la zona.
        columns:
          - name: estado_num
            description: >
              numero de identificacion de cada estado, corresponde a la columna cvegeoedo
              de la tabla staging.estados.
            
          - name: municipio_num
            description: >
              numero de identificacion de cada municipio, corresponde a la columna cvegeomuni.
              de la tabla staging.municipios
            
          - name: municipio
            description: Nombre del municipio
            
          - name: fecha
            description: Fecha en formato YYYYMMDD a la que corresponde el registro.
             
          - name: inicio
            description: >
              Fecha en formato timestamp en milisegundos desde el epoch, marca el inicio de la
              ventana de tiempo de los datos recolectados.
            
          - name: fin
            description:  >
              Fecha en formato timestamp en milisegundos desde el epoch, marca el fin de la
              ventana de tiempo de los datos recolectados.
            name: ndvi
            description: >
              Índice de vegetación de diferencia normalizada. Tamaño de pixel: 463.313m. Rango: -1 - 1.

      - name: nasa_surface_weather_historic
        description: >
          Contiene datos climatológicos en granularidad diaria obtenidos por municipio.
        columns:
          - name: estado_num
            description: >
              numero de identificacion de cada estado, corresponde a la columna cvegeoedo
              de la tabla staging.estados.
            
          - name: municipio_num
            description: >
              numero de identificacion de cada municipio, corresponde a la columna cvegeomuni.
              de la tabla staging.municipios
            
          - name: municipio
            description: Nombre del municipio
            
          - name: fecha
            description: Fecha en formato YYYYMMDD a la que corresponde el registro.
             
          - name: inicio
            description: >
              Fecha en formato timestamp en milisegundos desde el epoch, marca el inicio de la
              ventana de tiempo de los datos recolectados.
            
          - name: fin
            description:  >
              Fecha en formato timestamp en milisegundos desde el epoch, marca el fin de la
              ventana de tiempo de los datos recolectados.
            
          - name: dayl
            description: >
              duración del periodo de luz de día, basado en el periodo del dia durante el cual el sol está
              arriba de un horizonte plano hipotético. Unidad: Segundos. Rango: 0 - 86400.
            
          - name: prcp
            description: >
              Precipitación total diaria, sumatoria de todas las formas convertidos a equivalentes en agua.
              Unidad: mm. Rango: 0 - 544. 
            
          - name: srad
            description: >
              Densidad de flujo de radiación de onda corta incidente, tomada como un promedio durante 
              el período de luz diurna del día. Unidad: W/m**2. Rango: 0 - 1051.
                        
          - name: swe
            description: >
              Equivalente del agua de nieve, la cantidad de agua contenida dentro de una capa de nieve
              Unidad kg/m**2. Rango 0 - 13931.              
            
          - name: tmax
            description: >
              Temperatura del aire máxima diaria de 2 metros. Unidad: °C. Rango: -60 - 60. 
            
          - name: tmin
            description: >
              Temperatura del aire mínima diaria de 2 metros. Unidad: °C. Rango: -60 - 42.
            
          - name: vp
            description: >
              Presión de vapor de agua promedio parcial. Unidad: Pa. Rango: 0 - 8230.

  - name: refined
    description: Este dataset se compone de datos historicos limpios desde 2010 a 2023
    database: dengueappdb
    schema: refined
    tables:
      - name: clean_modis_ndvi_historic
        description: >
          Datos provenientes de la tabla staging.modis_ndvi_historic
        columns:
          - name: estado_num
            description: >
              numero de identificacion de cada estado, corresponde a la columna cvegeoedo
              de la tabla staging.estados.
            
          - name: municipio_num
            description: >
              numero de identificacion de cada municipio, corresponde a la columna cvegeomuni.
              de la tabla staging.municipios
            
          - name: municipio
            description: Nombre del municipio
            
          - name: fecha
            description: Fecha en formato YYYYMMDD a la que corresponde el registro.
             
          - name: inicio
            description: >
              Fecha en formato timestamp en milisegundos desde el epoch, marca el inicio de la
              ventana de tiempo de los datos recolectados.
            
          - name: fin
            description:  >
              Fecha en formato timestamp en milisegundos desde el epoch, marca el fin de la
              ventana de tiempo de los datos recolectados.
            name: ndvi
            description: >
              Índice de vegetación de diferencia normalizada. Tamaño de pixel: 463.313m. Rango: -1 - 1.
            name: num_de_semana
            description: >
              numero de la semana

      - name: clean_nasa_surface_weather_historic
        description: >
          Datos provenientes de staging.nasa_surface_weather_historic.
        columns:
          - name: estado_num
            description: >
              numero de identificacion de cada estado, corresponde a la columna cvegeoedo
              de la tabla staging.estados.
            
          - name: municipio_num
            description: >
              numero de identificacion de cada municipio, corresponde a la columna cvegeomuni.
              de la tabla staging.municipios
            
          - name: municipio
            description: Nombre del municipio
            
          - name: fecha
            description: Fecha en formato YYYYMMDD a la que corresponde el registro.
             
          - name: inicio
            description: >
              Fecha en formato timestamp en milisegundos desde el epoch, marca el inicio de la
              ventana de tiempo de los datos recolectados.
            
          - name: fin
            description:  >
              Fecha en formato timestamp en milisegundos desde el epoch, marca el fin de la
              ventana de tiempo de los datos recolectados.
            
          - name: dayl
            description: >
              duración del periodo de luz de día, basado en el periodo del dia durante el cual el sol está
              arriba de un horizonte plano hipotético. Unidad: Segundos. Rango: 0 - 86400.
            
          - name: prcp
            description: >
              Precipitación total diaria, sumatoria de todas las formas convertidos a equivalentes en agua.
              Unidad: mm. Rango: 0 - 544. 
            
          - name: srad
            description: >
              Densidad de flujo de radiación de onda corta incidente, tomada como un promedio durante 
              el período de luz diurna del día. Unidad: W/m**2. Rango: 0 - 1051.
                        
          - name: swe
            description: >
              Equivalente del agua de nieve, la cantidad de agua contenida dentro de una capa de nieve
              Unidad kg/m**2. Rango 0 - 13931.              
            
          - name: tmax
            description: >
              Temperatura del aire máxima diaria de 2 metros. Unidad: °C. Rango: -60 - 60. 
            
          - name: tmin
            description: >
              Temperatura del aire mínima diaria de 2 metros. Unidad: °C. Rango: -60 - 42.
            
          - name: vp
            description: >
              Presión de vapor de agua promedio parcial. Unidad: Pa. Rango: 0 - 8230.

          - name: num_de_semana
            description: >
              Número de la semana

      - name: reportes_combinados
        columns:
          - name: anio
          - name: cvegeoedo
          - name: cve_mun
          - name: municipio
          - name: indicador
          - name: unidad_de_medida        
          - name: enero
          - name: febrero
          - name: marzo
          - name: abril
          - name: mayo
          - name: junio
          - name: julio
          - name: agosto
          - name: septiembre
          - name: octubre
          - name: noviembre
          - name: diciembre

  - name: reportes
    description: Este dataset se componde de datos historicos desde 2010 hasta 2024 de casos de dengue mensuales ne jalisco por municipio
    database: dengueappdb
    schema: staging
    tables:
      - name: "2010"
        columns:
          - name: Enero
          - name: Febrero
          - name: Marzo
          - name: Abril
          - name: Mayo
          - name: Junio
          - name: Julio
          - name: Agosto
          - name: Septiembre
          - name: Octubre
          - name: Noviembre
          - name: Diciembre
          - name: Indicador
          - name: "Unidad de medida"

      - name: "2011"
        columns:
          - name: Enero
          - name: Febrero
          - name: Marzo
          - name: Abril
          - name: Mayo
          - name: Junio
          - name: Julio
          - name: Agosto
          - name: Septiembre
          - name: Octubre
          - name: Noviembre
          - name: Diciembre
          - name: Indicador
          - name: "Unidad de medida"

      - name: "2012"
        columns:
          - name: Enero
          - name: Febrero
          - name: Marzo
          - name: Abril
          - name: Mayo
          - name: Junio
          - name: Julio
          - name: Agosto
          - name: Septiembre
          - name: Octubre
          - name: Noviembre
          - name: Diciembre
          - name: Indicador
          - name: "Unidad de medida"

      - name: "2013"
        columns:
          - name: Enero
          - name: Febrero
          - name: Marzo
          - name: Abril
          - name: Mayo
          - name: Junio
          - name: Julio
          - name: Agosto
          - name: Septiembre
          - name: Octubre
          - name: Noviembre
          - name: Diciembre
          - name: Indicador
          - name: "Unidad de medida"

      - name: "2014"
        columns:
          - name: Enero
          - name: Febrero
          - name: Marzo
          - name: Abril
          - name: Mayo
          - name: Junio
          - name: Julio
          - name: Agosto
          - name: Septiembre
          - name: Octubre
          - name: Noviembre
          - name: Diciembre
          - name: Indicador
          - name: "Unidad de medida"

      - name: "2015"
        columns:
          - name: Enero
          - name: Febrero
          - name: Marzo
          - name: Abril
          - name: Mayo
          - name: Junio
          - name: Julio
          - name: Agosto
          - name: Septiembre
          - name: Octubre
          - name: Noviembre
          - name: Diciembre
          - name: Indicador
          - name: "Unidad de medida"

      - name: "2016"
        columns:
          - name: Enero
          - name: Febrero
          - name: Marzo
          - name: Abril
          - name: Mayo
          - name: Junio
          - name: Julio
          - name: Agosto
          - name: Septiembre
          - name: Octubre
          - name: Noviembre
          - name: Diciembre
          - name: Indicador
          - name: "Unidad de medida"

      - name: "2017"
        columns:
          - name: Enero
          - name: Febrero
          - name: Marzo
          - name: Abril
          - name: Mayo
          - name: Junio
          - name: Julio
          - name: Agosto
          - name: Septiembre
          - name: Octubre
          - name: Noviembre
          - name: Diciembre
          - name: Indicador
          - name: "Unidad de medida"

      - name: "2018"
        columns:
          - name: Enero
          - name: Febrero
          - name: Marzo
          - name: Abril
          - name: Mayo
          - name: Junio
          - name: Julio
          - name: Agosto
          - name: Septiembre
          - name: Octubre
          - name: Noviembre
          - name: Diciembre
          - name: Indicador
          - name: "Unidad de medida"

      - name: "2019"
        columns:
          - name: Enero
          - name: Febrero
          - name: Marzo
          - name: Abril
          - name: Mayo
          - name: Junio
          - name: Julio
          - name: Agosto
          - name: Septiembre
          - name: Octubre
          - name: Noviembre
          - name: Diciembre
          - name: Indicador
          - name: "Unidad de medida"

      - name: "2020"
        columns:
          - name: Enero
          - name: Febrero
          - name: Marzo
          - name: Abril
          - name: Mayo
          - name: Junio
          - name: Julio
          - name: Agosto
          - name: Septiembre
          - name: Octubre
          - name: Noviembre
          - name: Diciembre
          - name: Indicador
          - name: "Unidad de medida"

      - name: "2021"
        columns:
          - name: Enero
          - name: Febrero
          - name: Marzo
          - name: Abril
          - name: Mayo
          - name: Junio
          - name: Julio
          - name: Agosto
          - name: Septiembre
          - name: Octubre
          - name: Noviembre
          - name: Diciembre
          - name: Indicador
          - name: "Unidad de medida"

      - name: "2022"
        columns:
          - name: Enero
          - name: Febrero
          - name: Marzo
          - name: Abril
          - name: Mayo
          - name: Junio
          - name: Julio
          - name: Agosto
          - name: Septiembre
          - name: Octubre
          - name: Noviembre
          - name: Diciembre
          - name: Indicador
          - name: "Unidad de medida"

      - name: "2023"
        columns:
          - name: Enero
          - name: Febrero
          - name: Marzo
          - name: Abril
          - name: Mayo
          - name: Junio
          - name: Julio
          - name: Agosto
          - name: Septiembre
          - name: Octubre
          - name: Noviembre
          - name: Diciembre
          - name: Indicador
          - name: "Unidad de medida"

      - name: "2024"
        columns:
          - name: Enero
          - name: Febrero
          - name: Marzo
          - name: Abril
          - name: Mayo
          - name: Junio
          - name: Julio
          - name: Agosto
          - name: Septiembre
          - name: Octubre
          - name: Noviembre
          - name: Diciembre
          - name: Indicador
          - name: "Unidad de medida"

  - name: promedios_mensuales
    description: Este dataset se compone de datos historicos limpios desde 2010 a 2023
    database: dengueappdb
    schema: analytics
    tables:
      - name: promedios_mensuales_surfaceweather
        description: promeidos mensuales sw
        columns:      
          - name: anio
          - name: mes
          - name: municipio_num
          - name: dayl
          - name: prcp
          - name: srad
          - name: swe
          - name: tmax
          - name: tmin
          - name: vp

      - name: promedios_mensuales_ndvi
        description: promedios mensuales ndvi
        columns:
          - name: anio
            data_type: char(4)
          - name: mes
            data_type: char(2)
          - name: municipio_num
            data_type: char(5)
          - name: ndvi