version: 2

sources:
  - name: raw_data
    description:  "Datos crudos"
    database: dengueapp
    schema: rawdata
    tables:
      - name: estados
        descripcion: "descripcion estados"
        columns:
          - name: cvegeoedo
          - name: nom_edo

      - name: fuentes
        columns:
          - name: descripcion
          - name: estado
          - name: fecha_activacion
          - name: fecha_desactivacion
          - name: feacha_ultimo_cambio
          - name: nombre
          - name: url
            data_tests:
              - url_valido

      - name: municipios
        columns:
          - name: cvegeoedo
          - name: cvegeomuni
          - name: cve_mun
          - name: nom_mun
      
      - name: tipos
        columns:
          - name: codig
            data_tests:
              - not_null
              - unique
              - accepted_values:
                  values: ['ndvi','daily','prcp','srad','swe','tmax','tmin','vp']
            
      - name: modis_ndvi_historic
                        
      - name: nasa_surface_weather_historic
      
      - name: "2010"
        descripcion: "Casos mensuales de dengue por municipio de jalisco en el anio 2010. Granularidad: municipio"
            
      - name: "2011"
        descripcion: "Casos mensuales de dengue por municipio de jalisco en el anio 2011. Granularidad: municipio"

      - name: "2012"
        descripcion: "Casos mensuales de dengue por municipio de jalisco en el anio 2012. Granularidad: municipio"

      - name: "2013"
        descripcion: "Casos mensuales de dengue por municipio de jalisco en el anio 2013. Granularidad: municipio"
            
      - name: "2014"
        descripcion: "Casos mensuales de dengue por municipio de jalisco en el anio 2014. Granularidad: municipio"
            
      - name: "2015"
        descripcion: "Casos mensuales de dengue por municipio de jalisco en el anio 2015. Granularidad: municipio"
            
      - name: "2016"
        descripcion: "Casos mensuales de dengue por municipio de jalisco en el anio 2016. Granularidad: municipio"
            
      - name: "2017"
        descripcion: "Casos mensuales de dengue por municipio de jalisco en el anio 2017. Granularidad: municipio"
            
      - name: "2018"
        descripcion: "Casos mensuales de dengue por municipio de jalisco en el anio 2018. Granularidad: municipio"
            
      - name: "2019"
        descripcion: "Casos mensuales de dengue por municipio de jalisco en el anio 2019. Granularidad: municipio"
            
      - name: "2020"
        descripcion: "Casos mensuales de dengue por municipio de jalisco en el anio 2020. Granularidad: municipio"
            
      - name: "2021"
        descripcion: "Casos mensuales de dengue por municipio de jalisco en el anio 2021. Granularidad: municipio"
            
      - name: "2022"
        descripcion: "Casos mensuales de dengue por municipio de jalisco en el anio 2022. Granularidad: municipio"
            
      - name: "2023"
        descripcion: "Casos mensuales de dengue por municipio de jalisco en el anio 2023. Granularidad: municipio"
            
      - name: "2024"
        descripcion: "Casos mensuales de dengue por municipio de jalisco en el anio 2024. Granularidad: municipio"