name: DBT test and merge

on:
  push:
    branches:
      - '!main'
      - 'dbt_app/**'
      - '!extract_app/**'

    paths:
      - '!.github/**'
      - '!apps/extract_app/**'
      - '!environments/dev/extract_app/**'
      - 'apps/dbt_app/**'

jobs:
  code_test:
    name: Code test
    runs-on: ubuntu-latest
    outputs:
      not_failures: ${{steps.run_tests.outputs.not_failures}}
    environment: development
    env:
      DBT_ENV_SECRET_DATABASE: ${{ secrets.PGDATABASE }}
      DBT_ENV_SECRET_HOST: ${{ secrets.PGHOST }}
      DBT_PORT: ${{ secrets.PGPORT }}
      DBT_ENV_SECRET_USERSTG: ${{ secrets.PGUSERSTG }}
      DBT_ENV_SECRET_PASSWORDSTG: ${{ secrets.PGPASSWORDSTG }}
      DBT_ENV_SECRET_USERRFND: ${{ secrets.PGUSERRFND }}
      DBT_ENV_SECRET_PASSWORDRFND: ${{ secrets.PGPASSWORDRFND }}
      DBT_ENV_SECRET_USERANLST: ${{ secrets.PGUSERANLST }}
      DBT_ENV_SECRET_PASSWORDANLST: ${{ secrets.PGPASSWORDANLST }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        working-directory: apps/dbt_app/
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: extract test file name
        run: |
          BRANCH_NAME="${{ github.ref_name }}"
          TEST_FILE="test_${BRANCH_NAME#*/}.sh"
          echo "TEST_FILE=$TEST_FILE" >> $GITHUB_ENV

      - name: Run tests and capture output
        id: run_tests
        working-directory: apps/dbt_app/tests/    
        run: |
          chmod +x $TEST_FILE
          . $TEST_FILE

      - name: Send email with test results
        if: steps.run_tests.outputs.not_failures == 'false'
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "❌ Pytest Failures for Commit ${{ github.sha }}"
          to: renegarciabernal.rg@gmail.com #replace with team emails
          from: GitHub CI Bot <${{ secrets.EMAIL_USERNAME }}>
          body: |
            Hello,

            Here are the test results from GitHub Actions:

            ${{ steps.run_tests.outputs.test_output }}

  create_merge_and_cleanup:
    name: Create, Auto-Merge PR & Delete Branch
    needs: code_test
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    env:
      PR_NUMBER: ${{ github.event.number }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Needed for full diff

      - name: Set up Git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh

      - name: Authenticate GitHub CLI
        run: |
          echo "${{ secrets.GH_PUSH_TOKEN }}" | gh auth login --with-token

      - name: Fetch main branch
        run: git fetch origin main

      - name: Check for differences with main
        id: check_diff
        run: |
          git diff --quiet origin/main..HEAD || echo "has_diff=true" >> $GITHUB_OUTPUT

      - name: Create PR if differences exist
        if: steps.check_diff.outputs.has_diff == 'true'
        run: |
            gh pr create \
            --base main \
            --head ${{ github.ref_name }} \
            --title "Auto PR: ${{ github.ref_name }} → main" \
            --body "This PR was created automatically after pushing changes to ${{ github.ref_name }}."

      - name: Merge PR
        run: |
          gh pr merge $PR_NUMBER \
            --auto \
            --merge \
            --delete-branch \
            --admin 