name: DBT test and merge

on:
  push:
    branches:
      - '!main'
      - 'dbt_app/**'
      - '!extract_app/**'

    paths:
      - '!.github/**'
      - '!apps/extract_app/**'
      - '!environments/dev/extract_app/**'
      - 'apps/dbt_app/**'

jobs:
  code_test:
    name: Code test
    runs-on: ubuntu-latest
    outputs:
      not_failures: ${{steps.run_tests.outputs.not_failures}}
    environment: development
    env:
      DBT_ENV_SECRET_DATABASE: ${{ secrets.PGDATABASE }}
      DBT_ENV_SECRET_HOST: ${{ secrets.PGHOST }}
      DBT_PORT: ${{ secrets.PGPORT }}
      DBT_ENV_SECRET_USERSTG: ${{ secrets.PGUSERSTG }}
      PDBT_ENV_SECRET_PASSWORDSTG: ${{ secrets.PGPASSWORDSTG }}
      DBT_ENV_SECRET_USERRFND: ${{ secrets.PGUSERRFND }}
      PDBT_ENV_SECRET_PASSWORDRFND: ${{ secrets.PGPASSWORDRFND }}
      DBT_ENV_SECRET_USERANLST: ${{ secrets.PGUSERANLST }}
      PDBT_ENV_SECRET_PASSWORDANLST: ${{ secrets.PGPASSWORDANLST }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # Change to your project's Python version

      - name: Install dependencies
        working-directory: apps/dbt_app/
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: extract test file name
        run: |
          BRANCH_NAME="${{ github.ref_name }}"
          TEST_FILE="test_${BRANCH_NAME#*/}.sh"
          echo "TEST_FILE=$TEST_FILE" >> $GITHUB_ENV

      - name: Run tests and capture output
        id: run_tests
        working-directory: apps/dbt_app/tests/    
        run: |
          chmod +x $TEST_FILE
          . $TEST_FILE

      - name: Send email with test results
        if: steps.run_tests.outputs.not_failures == 'false'
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "❌ Pytest Failures for Commit ${{ github.sha }}"
          to: renegarciabernal.rg@gmail.com #replace with team emails
          from: GitHub CI Bot <${{ secrets.EMAIL_USERNAME }}>
          body: |
            Hello,

            Here are the test results from GitHub Actions:

            ${{ steps.run_tests.outputs.test_output }}

  create_merge_and_cleanup:
    name: Create, Auto-Merge PR & Delete Branch
    needs: code_test
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get branch name
        id: vars
        run:  | 
          echo "${{ github.ref_name }}"
          echo "${GITHUB_REF#refs/heads/}"
        # echo "branch_name=${GITHUB_REF#refs/heads/}"
        #  echo "branch_name=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT
        # run: echo "branch_name=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT

      # - name: Create Pull Request
      #   id: create_pr
      #   uses: peter-evans/create-pull-request@v5
      #   with:
      #     token: ${{ secrets.GH_PUSH_TOKEN }}
      #     commit-message: "Auto PR: Merging ${{ steps.vars.outputs.branch_name }}"
      #     title: "Auto PR for ${{ steps.vars.outputs.branch_name }}"
      #     body: "This PR was created automatically after successful tests."
      #     base: main
      #     branch: ${{ github.ref_name }}
      #     # branch: ${{ steps.vars.outputs.branch_name }}
      #     delete-branch: true
      #     labels: automerge

      # - name: Enable Auto-Merge
      #   uses: peter-evans/enable-pull-request-automerge@v2
      #   with:
      #     token: ${{ secrets.GH_PUSH_TOKEN }}
      #     pull-request-number: ${{ steps.create_pr.outputs.pull-request-number }}
      #     merge-method: merge

      # - name: Delete merged branch
      #   run: |
      #     gh api -X DELETE repos/${{ github.repository }}/git/refs/heads/${{ steps.vars.outputs.branch_name }}
        # env:
        #   GH_TOKEN: ${{ secrets.GH_PUSH_TOKEN }}
