name: Test, Merge & Deploy

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  test-and-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r apps/extract_app/requirements.txt

      - name: Run tests
        id: run_tests
        run: |
          pytest apps/extract_app/tests/ > result.log || echo "FAILED" > fail_flag

      - name: Check test result
        id: check_result
        run: |
          if [ -f fail_flag ]; then
            echo "Tests failed"
            echo "status=failed" >> $GITHUB_OUTPUT
          else
            echo "Tests passed"
            echo "status=passed" >> $GITHUB_OUTPUT
          fi

      - name: Auto merge if tests passed
        if: steps.check_result.outputs.status == 'passed'
        uses: pascalgn/automerge-action@v0.16.3
        with:
          merge-method: squash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image to GHCR
        if: steps.check_result.outputs.status == 'passed'
        run: |
          echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker build -t ghcr.io/${{ github.repository }}/my-app:latest .
          docker push ghcr.io/${{ github.repository }}/my-app:latest

      - name: Send email if tests failed
        if: steps.check_result.outputs.status == 'failed'
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Test Failed on PR #${{ github.event.pull_request.number }}"
          to: ${{ github.event.pull_request.user.email }}
          from: GitHub CI Bot <${{ secrets.EMAIL_USERNAME }}>
          body: |
            Hello ${{ github.event.pull_request.user.login }},
            Your PR #${{ github.event.pull_request.number }} has failed tests.

            Test output:
            ----------------
            ${{ steps.run_tests.outputs.result }}
