version: 2

sources:
  - name: historic
    description: Este dataset se compone de datos historicos desde 2010 a 2023
    database: dengueappdb
    schema: staging
    tables:
      - name: modis_ndvi_historic
        description: >
          Contiene datos obtenidos por el satelite modis en granularidad diaria, por municipio.
          el ndvi (Natural Data Vegetation Index) indica la salud de la vegetación en la zona.
        columns:
          - name: estado_num
            description: >
              numero de identificacion de cada estado, corresponde a la columna cvegeoedo
              de la tabla staging.estados.
            
          - name: municipio_num
            description: >
              numero de identificacion de cada municipio, corresponde a la columna cvegeomuni.
              de la tabla staging.municipios
            
          - name: municipio
            description: Nombre del municipio
            
          - name: fecha
            description: Fecha en formato YYYYMMDD a la que corresponde el registro.
             
          - name: inicio
            description: >
              Fecha en formato timestamp en milisegundos desde el epoch, marca el inicio de la
              ventana de tiempo de los datos recolectados.
            
          - name: fin
            description:  >
              Fecha en formato timestamp en milisegundos desde el epoch, marca el fin de la
              ventana de tiempo de los datos recolectados.
            name: ndvi
            description: >
              Índice de vegetación de diferencia normalizada. Tamaño de pixel: 463.313m. Rango: -1 - 1.

      - name: nasa_surface_weather_historic
        description: >
          Contiene datos climatológicos en granularidad diaria obtenidos por municipio.
        columns:
          - name: estado_num
            description: >
              numero de identificacion de cada estado, corresponde a la columna cvegeoedo
              de la tabla staging.estados.
            
          - name: municipio_num
            description: >
              numero de identificacion de cada municipio, corresponde a la columna cvegeomuni.
              de la tabla staging.municipios
            
          - name: municipio
            description: Nombre del municipio
            
          - name: fecha
            description: Fecha en formato YYYYMMDD a la que corresponde el registro.
             
          - name: inicio
            description: >
              Fecha en formato timestamp en milisegundos desde el epoch, marca el inicio de la
              ventana de tiempo de los datos recolectados.
            
          - name: fin
            description:  >
              Fecha en formato timestamp en milisegundos desde el epoch, marca el fin de la
              ventana de tiempo de los datos recolectados.
            
          - name: dayl
            description: >
              duración del periodo de luz de día, basado en el periodo del dia durante el cual el sol está
              arriba de un horizonte plano hipotético. Unidad: Segundos. Rango: 0 - 86400.
            
          - name: prcp
            description: >
              Precipitación total diaria, sumatoria de todas las formas convertidos a equivalentes en agua.
              Unidad: mm. Rango: 0 - 544. 
            
          - name: srad
            description: >
              Densidad de flujo de radiación de onda corta incidente, tomada como un promedio durante 
              el período de luz diurna del día. Unidad: W/m**2. Rango: 0 - 1051.
                        
          - name: swe
            description: >
              Equivalente del agua de nieve, la cantidad de agua contenida dentro de una capa de nieve
              Unidad kg/m**2. Rango 0 - 13931.              
            
          - name: tmax
            description: >
              Temperatura del aire máxima diaria de 2 metros. Unidad: °C. Rango: -60 - 60. 
            
          - name: tmin
            description: >
              Temperatura del aire mínima diaria de 2 metros. Unidad: °C. Rango: -60 - 42.
            
          - name: vp
            description: >
              Presión de vapor de agua promedio parcial. Unidad: Pa. Rango: 0 - 8230.
